**

diff --git a/setup/resources/bash/nepi_docker_aliases b/setup/resources/bash/nepi_docker_aliases
--- a/setup/resources/bash/nepi_docker_aliases
+++ b/setup/resources/bash/nepi_docker_aliases
@@ -74,84 +74,211 @@ else
 fi
 
 
+###################################
+# NEPI DEV Util Functions
+###################################
+export SOURCE_FOLDER=/home/${USER}/nepi_engine_ws
+GREEN='\033[0;32m'
+RED='\033[0;31m'
+
+## NEPI deploy complete
+alias nepidpl="
+cd $SOURCE_FOLDER
+./deploy_nepi_complete.sh"
+
+# NEPI deploy repos
+alias repodpl="
+cd $SOURCE_FOLDER
+./deploy_nepi_repos.sh"
+
+utilsn="${utilsn}
+### NEPI DEV UTIL FUNCTIONS
+nepidpl = deploy nepi complete
+repodpl = deploy specific repos"
+
+function pushn(){
+  git add --all
+  git commit -m "*$@*" 
+  git push
+  cur_folder=${PWD##*/}
+  par_path=$(dirname "$(pwd)")
+  par_folder=${par_path##/*}
+  if [[ "$cur_folder" != 'nepi_engine_ws' || "$par_folder" != 'nepi_engine_ws' ]]; then
+    echo -e "${GREEN}Pushing to repo ${PWD##*/} Head ros1_main"
+    git push origin HEAD:ros1_main
+    if [ ! $? -eq 0 ]; then
+      echo -e "${RED}Push Failed"
+      return 1 # Failed
+    fi
+  fi
+  echo -e "${GREEN}Push Successfully"
+}
+
+
+function pushna(){
+  failed=0
+  if [ -d "$SOURCE_FOLDER" ]; then
+    commit_comment=*$@*
+    src_folder=${SOURCE_FOLDER}/src
+    cd $src_folder
+    for d1 in */; do
+      if [ -d "$d1" ]; then
+
+        rep_folder=${src_folder}/${d1}
+        echo ""
+        echo ""
+        echo "Processing Repo ${d1}"
+        echo "*********************"
+        echo ""
+        cd ${rep_folder}
+        echo 1
+        for d2 in */; do
+          echo $d2
+          if [ -d "$d2" ]; then
+            echo 3
+            proj_folder=${rep_folder}/${d2}
+            echo 4
+            cd ${proj_folder}
+            echo 5
+            if [ -f "${proj_folder}/.git" ]; then
+              echo 6
+              echo ""
+              echo "${d2}"
+              echo "--------------------"
+              failed=pushn $commit_comment
+              echo "Pushed ${d2}"
+              if [[ "failed" -eq 1 ]]; then
+                break
+              fi
+            fi
+          fi
+        done
+        cd ${rep_folder}
+        if [ -f "${rep_folder}/.git" and "$failed" -eq 0 ]; then
+            echo ""
+            echo "${d1}"
+            echo "--------------------"
+            failed=pushn $commit_comment
+            echo "Pushed ${d1}"
+            if [[ "$failed" -eq 1 ]]; then
+              break
+            fi
+        fi
+        cd $src_folder
+      fi
+    done
+    cd ${SOURCE_FOLDER}
+    if [ "$failed" -e 0 ]; then
+      echo ""
+
+      echo "nepi_engine_ws"
+      echo "--------------------"
+      pushn $commit_comment
+      if [[ $? -eq 1S ]]; then
+        success=0
+      fi
+    fi
+  fi
+}
+
+utilsn="${utilsn}
+### NEPI DEV UTIL FUNCTIONS
+nepidpl = Deploy nepi complete to nepi device
+repodpl = Deploy repos to nepi device
+pushn = Add,commit,push repo changes with provided comment"
+
+
+###################################
+# NEPI SYSTEM Util Functions
+###################################
+
+
+
 #############################
 # NEPI DOCKER FUNCTIONS
 #############################
 
+export NEPI_USER=nepi
+export NEPI_HOME=/home/nepi
 
-function create_tag(){
-    SW_VERSION=$1
-    HW_TYPE=$2
-    HW_MODEL=$3
-    
-    TAG_VARIABLE=$4
-    tag=${SW_VERSION}-${HW_TYPE}-${HW_MODEL}
-    export TAG_VARIABLE="${tag,,}" # Convert to lowercase
-    echo "$TAG_VARIABLE"
+
+export NEPI_SYSTEM_CONFIG=/opt/nepi/nepi_engine/etc
+export NEPI_CONFIG=${NEPI_SYSTEM_CONFIG}/.nepi_system_config.yaml
+export NEPI_STORAGE=/mnt/nepi_storage
+
+alias nepihome="
+cd ${NEPI_HOME}"
+
+function nepienable(){
+    sudo systemctl enable nepi_docker
 }
-export -f create_tag
 
-######################
-# COMMIT_NEPI
-######################
-function commit_nepi(){
-    # Commit the Running Container
-    if [[ ! -v NEPI_RUNNING ]]; then
-        if [[ ( -v NEPI_RUNNING && "$NEPI_RUNNING" -eq 1 ) ]]; then
-            echo "Stopping Running NEPI Docker Process ${NEPI_RUNNING_NAME}:${NEPI_RUNNING_TAG} ID:${NEPI_RUNNING_ID}"
-            dcommit $NEPI_RUNNING_ID ${1}:${2}
-        else
-            echo "No Running NEPI Contatainer to Commit"
-        fi
-    else
-        echo "Failed to Read NEPI Docker Config File"
-        exit 1
-    fi 
+function nepidisable(){
+    sudo systemctl disable nepi_docker
 }
-export -f commit_nepi
 
-######################
-# LOGIN_NEPI
-######################
-function login_nepi(){
+# NEPI stop and start shortcuts
+function nepistop(){
+
+  . ${NEPI_DOCKER_CONFIG}/nepi_docker_stop.sh
+}
+
+function nepistart(){
+    . ${NEPI_DOCKER_CONFIG}/nepi_docker_start.sh
+}
+
+
+function nepilogin(){
   . ${NEPI_DOCKER_CONFIG}/nepi_docker_login.sh   
 }
 export -f login_nepi
 
-######################
-# SWITCH_NEPI
-######################
-function switch_nepi(){
+
+
+function nepicommit(){
+  . ${NEPI_DOCKER_CONFIG}/nepi_docker_commit.sh
+}
+export -f commit_nepi
+
+
+
+function nepiswitch(){
   . ${NEPI_DOCKER_CONFIG}/nepi_docker_switch.sh
 }
 export -f switch_nepi
 
-######################
-# IMPORT_NEPI
-######################
 
-function import_nepi(){
+function nepiimport(){
   . ${NEPI_DOCKER_CONFIG}/nepi_docker_import.sh
 }
 export -f import_nepi
 
-######################
-# EXPORT_NEPI
-######################
 
-function export_nepi(){
+function nepiexport(){
   . ${NEPI_DOCKER_CONFIG}/nepi_docker_export.sh
 }
 export -f export_nepi
+
+# copy arvhived images to install folder
+function ndhcp(){
+  :
+}
+
 
 HELPN="${HELPN}
 ################################
 ## NEPI Docker Functions ##
 ################################
-create_tag = Create a docker tag given SW_VERSION HW_TYPE HW_MODEL TAG_VARIABLE
-commit_nepi = Commit the running nepi container
-login_nepi = Log into the running nepi container
-switch_nepi = Switch to Inactive NEPI container on next boot or reststat"
+nepihome = Switch to NEPI home folder
+nepienable = Enable NEPI Docker Service on Startup
+nepidisable = Disable NEPI Docker Service on Startup
+nepistart = Start the nepi docker container
+nepistop = Stop the running nepi docker container
+nepilogin = Log into the running nepi container
+nepiswitch = Switch to Inactive NEPI container on next boot or reststat
+nepicommit = Commit the running nepi container
+nepiimport = Commit the running nepi container
+nepiexport = Commit the running nepi container"
 
 
 ###################################
diff --git a/setup/resources/bash/nepi_pc_aliases b/setup/resources/bash/nepi_pc_aliases
--- a/setup/resources/bash/nepi_pc_aliases
+++ b/setup/resources/bash/nepi_pc_aliases
@@ -68,11 +68,124 @@ else
   start_ssh_agent;
 fi
 
-
-
 ###################################
+# NEPI DEV Util Functions
+###################################
+export SOURCE_FOLDER=/home/${USER}/nepi_engine_ws
+GREEN='\033[0;32m'
+RED='\033[0;31m'
+
+## NEPI deploy complete
+alias nepidpl="
+cd $SOURCE_FOLDER
+./deploy_nepi_complete.sh"
+
+# NEPI deploy repos
+alias repodpl="
+cd $SOURCE_FOLDER
+./deploy_nepi_repos.sh"
+
+utilsn="${utilsn}
+### NEPI DEV UTIL FUNCTIONS
+nepidpl = deploy nepi complete
+repodpl = deploy specific repos"
+
+function pushn(){
+  git add --all
+  git commit -m "*$@*" 
+  git push
+  cur_folder=${PWD##*/}
+  par_path=$(dirname "$(pwd)")
+  par_folder=${par_path##/*}
+  if [[ "$cur_folder" != 'nepi_engine_ws' || "$par_folder" != 'nepi_engine_ws' ]]; then
+    echo -e "${GREEN}Pushing to repo ${PWD##*/} Head ros1_main"
+    git push origin HEAD:ros1_main
+    if [ ! $? -eq 0 ]; then
+      echo -e "${RED}Push Failed"
+      return 1 # Failed
+    fi
+  fi
+  echo -e "${GREEN}Push Successfully"
+}
+
+
+function pushna(){
+  failed=0
+  if [ -d "$SOURCE_FOLDER" ]; then
+    commit_comment=*$@*
+    src_folder=${SOURCE_FOLDER}/src
+    cd $src_folder
+    for d1 in */; do
+      if [ -d "$d1" ]; then
+
+        rep_folder=${src_folder}/${d1}
+        echo ""
+        echo ""
+        echo "Processing Repo ${d1}"
+        echo "*********************"
+        echo ""
+        cd ${rep_folder}
+        echo 1
+        for d2 in */; do
+          echo $d2
+          if [ -d "$d2" ]; then
+            echo 3
+            proj_folder=${rep_folder}/${d2}
+            echo 4
+            cd ${proj_folder}
+            echo 5
+            if [ -f "${proj_folder}/.git" ]; then
+              echo 6
+              echo ""
+              echo "${d2}"
+              echo "--------------------"
+              failed=pushn $commit_comment
+              echo "Pushed ${d2}"
+              if [[ "failed" -eq 1 ]]; then
+                break
+              fi
+            fi
+          fi
+        done
+        cd ${rep_folder}
+        if [ -f "${rep_folder}/.git" and "$failed" -eq 0 ]; then
+            echo ""
+            echo "${d1}"
+            echo "--------------------"
+            failed=pushn $commit_comment
+            echo "Pushed ${d1}"
+            if [[ "$failed" -eq 1 ]]; then
+              break
+            fi
+        fi
+        cd $src_folder
+      fi
+    done
+    cd ${SOURCE_FOLDER}
+    if [ "$failed" -e 0 ]; then
+      echo ""
+
+      echo "nepi_engine_ws"
+      echo "--------------------"
+      pushn $commit_comment
+      if [[ $? -eq 1S ]]; then
+        success=0
+      fi
+    fi
+  fi
+}
+
+utilsn="${utilsn}
+### NEPI DEV UTIL FUNCTIONS
+nepidpl = Deploy nepi complete to nepi device
+repodpl = Deploy repos to nepi device
+pushn = Add,commit,push repo changes with provided comment"
+
+
+
 ###################################
 #NEPI folder shortcuts
+###################################
 export AI="/mnt/nepi_storage/ai_models"
 export AIF="/opt/nepi/nepi_engine/share/nepi_ai_ifs"
 export API="/opt/nepi/nepi_engine/lib/python3/dist-packages/nepi_api"
